[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-essentialsbds"
version = "3.5.0"
description = "An essentials plugin for diagnostics, stability, and quality of life on Minecraft Bedrock Edition."
requires-python = ">=3.10"
author = "Onistone"
dependencies = [
    "endstone>=0.11.9,<0.12",
    "bedrock-protocol-packets-ng>=0.0.9",
    "mcbe-binarystream==2.1.0",
    "chest_form_api_endstone >= 1.0.0"
]

[project.entry-points."endstone"]
onistone_essentials = "endstone_primebds:OnistoneEssentials"

[tool.hatch.build.targets.wheel]
packages = ["src/endstone_primebds"]
